<?php

return [
    'brand' => [
        'name' => 'Gownsea LTD',
        'primary_color' => '#d42127',
        'phone' => '+254 728 311537',
        'email' => 'hello@gownsea.com',
        'address' => 'Valji Building, Moktar Daddah Street, Nairobi',
        'whatsapp' => '254728311537',
        'logo' => null,
    ],

    'assistant' => [
        'admin_email' => env('ASSISTANT_ADMIN_EMAIL', env('MAIL_FROM_ADDRESS', 'hello@gownsea.com')),
        'faqs' => [
            'Buying process' => 'How do I buy or hire a gown from Gownsea?',
            'Available properties' => 'What categories are currently available?',
            'Pricing' => 'How much does gown hire or purchase cost?',
            'Contact support' => 'How can I quickly contact support?',
        ],
    ],

    'protected_routes' => [
        '/',
        '/about-us',
        '/contact-us',
        '/legal-attire',
        '/graduation-attire',
        '/church-wear',
        '/gown-for-hire',
        '/shop-attire/graduation-attire',
        '/shop-attire/legal-attire',
        '/shop-attire/church-wear',
        '/bulk-inquiry',
        '/the-gown-journal',
        '/the-gown-journal/bulk-hiring-of-gowns-for-institutions-a-cost-effective-and-convenient-solution',
        '/the-gown-journal/why-renting-your-graduation-gown-is-a-smart-choice',
        '/the-gown-journal/what-your-grads-really-think-about-their-gowns-and-why-it-matters',
        '/privacy-policy',
        '/terms-and-conditions',
        '/return-policy',
        '/copyright',

        // Shop Attire (Graduation Attire dropdown)
        '/shop-attire-collection/graduation-attire/graduation-cap',
        '/our-products/graduation-tassels',
        '/our-products/undergraduate-academic-hoods',
        '/shop-attire-collection/graduation-attire/graduation-hoods',
        '/our-products/graduation-stoles',
        '/shop-attire-collection/graduation-attire/phd-caps',
        '/our-products/preschool-graduation',
        '/shop-attire-collection/graduation-attire/pre-school-gowns',
        '/shop-attire-collection/graduation-attire/certificate-gowns',
        '/shop-attire-collection/graduation-attire/diploma-gowns',
        '/shop-attire-collection/graduation-attire/masters-gowns',
        '/shop-attire-collection/graduation-attire/phd-gowns',
        '/our-products/phd-graduation-gown',
        '/shop-attire-collection/graduation-attire/degree-gown',
        '/our-products/degree-graduation-gowns',
        '/our-products/certificate-gowns',
        '/our-products/diploma-graduation-gowns',
        '/our-products/masters-gown',
        '/our-products/phd-caps',

    ],

    'hire_faqs' => [
        'How do I hire a graduation gown?' => 'Head to our gown hire page or bulk inquiry form and we will respond as soon as we can.',
        'How much is it to rent a gown?' => 'It varies by quantity and award level. Graduation hire currently starts from KES 2,500. Send an inquiry for an accurate quote.',
        'What do you wear under a university graduation gown?' => 'Dress smart for a formal occasion. A dark suit or formal dress works well under academic gowns.',
        'How much are graduation gowns in Kenya?' => 'Purchase and hire prices vary by award level. Browse the graduation collection or request a tailored quote.',
    ],

    'clients' => [
        '/images/clients/client-7.png',
        '/images/clients/client-8.png',
        '/images/clients/client-9.png',
        '/images/clients/client-10.png',
        '/images/clients/client-11.png',
        '/images/clients/client-13.png',
        '/images/clients/client-14.jpg',
        '/images/clients/client-15.png',
    ],

    'hire_products' => [
        [
            'slug' => 'graduation-stoles',
            'title' => 'Graduation Stoles',
            'location' => 'Nairobi',
            'price' => 'KES 1,500',
            'cta' => 'Request Gown Now',
            'description' => 'Ceremony-ready stoles to complete academic sets for hire or purchase.',
            'category' => 'graduation',
            'image' => '/images/products/Gownsea-custom-graduation-stoles-(23).png',
            'url' => '/our-products/graduation-stoles',
        ],
        [
            'slug' => 'graduation-tassels',
            'title' => 'Graduation Tassels',
            'location' => 'Nairobi',
            'price' => 'KES 350',
            'cta' => 'Request Gown Now',
            'description' => 'Colour-matched tassels for mortarboards across award levels.',
            'category' => 'graduation',
            'image' => '/images/products/graduation-tassels-from-gownsea-(4)-Photoroom-(1).jpg',
            'url' => '/our-products/graduation-tassels',
        ],
        [
            'slug' => 'certificate-gowns',
            'title' => 'Certificate Gowns',
            'location' => 'Nairobi',
            'price' => 'KES 2,500',
            'sale_price' => 'KES 2,500',
            'cta' => 'Hire Graduation Attire',
            'description' => 'Certificate-level gowns available for hire and sale.',
            'category' => 'graduation',
            'image' => '/images/products/Gownsea-certificate-graduation-gowns-black-(7).png',
            'url' => '/shop-attire-collection/graduation-attire/certificate-gowns',
        ],
        [
            'slug' => 'diploma-graduation-gowns',
            'title' => 'Diploma Graduation Gowns',
            'location' => 'Nairobi',
            'price' => 'KES 4,500',
            'cta' => 'Hire Graduation Attire',
            'description' => 'Diploma gowns prepared for ceremony hire with reliable sizing support.',
            'category' => 'graduation',
            'image' => '/images/products/Gownsea-diploma-graduation-gowns-(10)-Photoroom.png',
            'url' => '/shop-attire-collection/graduation-attire/diploma-gowns',
        ],
        [
            'slug' => 'degree-graduation-gowns',
            'title' => 'Degree Graduation Gowns',
            'location' => 'Nairobi',
            'price' => 'KES 6,500',
            'cta' => 'Hire Graduation Attire',
            'description' => 'University-standard degree gowns for hire across Kenyan institutions.',
            'category' => 'graduation',
            'image' => '/images/products/graduation-gowns-by-Gownsea-Caroline-muthoni-(42).1.png',
            'url' => '/our-products/degree-graduation-gowns',
        ],
        [
            'slug' => 'masters-gown',
            'title' => 'Masters Gown',
            'location' => 'Nairobi',
            'price' => 'KES 7,500',
            'cta' => 'Hire Graduation Attire',
            'description' => 'Masters gowns with the right academic finish for conferment ceremonies.',
            'category' => 'graduation',
            'image' => '/images/products/Masters-Graduation-(5)-Photorooms.png',
            'url' => '/our-products/masters-gown',
        ],
        [
            'slug' => 'preschool-graduation',
            'title' => 'Preschool Graduation',
            'location' => 'Nairobi',
            'price' => 'KES 3,000',
            'sale_price' => 'KES 2,500',
            'cta' => 'Hire Graduation Attire',
            'description' => 'Child-ready preschool graduation sets for schools and parents.',
            'category' => 'graduation',
            'image' => '/images/products/Preschool-graduation-gown-and-sash-(1).png',
            'url' => '/our-products/preschool-graduation',
        ],
        [
            'slug' => 'phd-caps',
            'title' => 'PHD Caps',
            'location' => 'Nairobi',
            'price' => 'KES 4,900',
            'cta' => 'Request Gown Now',
            'description' => 'Doctoral caps and bonnets to complete PhD regalia.',
            'category' => 'graduation',
            'image' => '/images/products/PhD-Graduation-cap.-Gownsea-ltd-(9)-Photoroom.jpg',
            'url' => '/shop-attire-collection/graduation-attire/phd-caps',
        ],
        [
            'slug' => 'phd-graduation-gown',
            'title' => 'PHD Graduation Gown',
            'location' => 'Nairobi',
            'price' => 'KES 18,500',
            'cta' => 'Hire Graduation Attire',
            'description' => 'Doctoral gowns for hire with a distinguished ceremonial finish.',
            'category' => 'graduation',
            'image' => '/images/products/PhD-Doctorate-graduation-gown-clergy-(20)-Photoroom.jpg',
            'url' => '/our-products/phd-graduation-gown',
        ],
        [
            'slug' => 'undergraduate-academic-hoods',
            'title' => 'Undergraduate Academic Hoods',
            'location' => 'Nairobi',
            'price' => 'KES 1,800',
            'cta' => 'Request Gown Now',
            'description' => 'Faculty-colour undergraduate hoods to complete degree sets.',
            'category' => 'graduation',
            'image' => '/images/products/academic-gradduation-hoods-hoods-(18)-Photoroom.jpg',
            'url' => '/our-products/undergraduate-academic-hoods',
        ],
    ],

    'properties' => [
        [
            'slug' => 'bachelors-graduation-gown-cap-hood-set',
            'title' => 'Bachelors Graduation Gown, Cap & Hood Set',
            'location' => 'Nairobi',
            'price' => 'KES 7,500',
            'sale_price' => 'KES 6,500',
            'cta' => 'Reserve Set',
            'description' => 'University-standard complete set for ceremonies and photo sessions.',
            'category' => 'graduation',
            'image' => '/images/products/graduation-gowns-by-Gownsea-Caroline-muthoni-(42).1.png',
            'url' => '/shop-attire-collection/graduation-attire/degree-gown',
        ],
        [
            'slug' => 'traditional-barrister-wig-and-gown',
            'title' => 'Traditional Barrister Wig & Gown',
            'location' => 'Nairobi CBD',
            'price' => 'KES 38,000',
            'cta' => 'Request Quote',
            'description' => 'Premium courtroom-ready legal attire tailored for professional use.',
            'category' => 'legal',
            'image' => '/images/site/barrister-wig.jpg',
            'url' => '/shop-attire/legal-attire',
        ],
        [
            'slug' => 'plain-english-bib',
            'title' => 'Bib',
            'location' => 'Nairobi',
            'price' => 'KES 500',
            'cta' => 'Shop Legal Wear',
            'description' => 'Courtroom bibs for advocates and barristers.',
            'category' => 'legal',
            'image' => '/images/products/Plain-English-Bib-New-1.jpg',
            'url' => '/shop-attire/legal-attire',
        ],
        [
            'slug' => 'advocates-shirt',
            'title' => 'Advocates Shirt',
            'location' => 'Nairobi',
            'price' => 'KES 2,600',
            'sale_price' => 'KES 2,600',
            'cta' => 'Shop Legal Wear',
            'description' => 'White advocates shirts for professional courtroom wear.',
            'category' => 'legal',
            'image' => '/images/products/advocate-white-shirts.jpeg',
            'url' => '/shop-attire/legal-attire',
        ],
        [
            'slug' => 'choral-and-church-attire-pack',
            'title' => 'Choral & Church Attire Pack',
            'location' => 'Nationwide Delivery',
            'price' => 'KES 8,700',
            'cta' => 'Order Pack',
            'description' => 'Elegant church wear with customized fitting for ministry teams.',
            'category' => 'church',
            'image' => '/images/products/Gownsea-church-wear-(1).png',
            'url' => '/shop-attire/church-wear',
        ],
    ],

    'product_profiles' => [
        'graduation-stoles' => [
            'description' => 'Complete graduation attire with a stole chosen to complement your gown, faculty colours, or institution identity. Ask Gownsea about options for individual graduates and group orders in Nairobi.',
            'details' => ['A finishing piece for graduation and academic regalia', 'Choose colours that complement your gown or institution', 'Suitable for individual enquiries and group planning', 'Ask about current hire and purchase options'],
            'about' => '<p>A graduation stole adds colour and personal meaning to an academic outfit. Select a shade that works with your gown and reflects the style of your institution or faculty.</p><p>Gownsea can help graduates and organisers plan stoles for a ceremony in Nairobi. Share the colours, quantity, and date you have in mind so the team can confirm available options and provide a suitable quote.</p>',
        ],
        'graduation-tassels' => [
            'description' => 'Find graduation tassels to complete mortarboards for school, college, or university ceremonies. Share your preferred colour and quantity with Gownsea to confirm a match for your graduation set.',
            'details' => ['Designed to finish a graduation mortarboard', 'Check colours against your institution’s requirements', 'Useful for individual orders and ceremony quantities', 'Confirm availability and the correct match before ordering'],
            'about' => '<p>A tassel is a small detail that makes a graduation cap feel complete. Choose a colour that follows your school or institution’s guidance, then pair it with the rest of your academic regalia for a coordinated ceremony look.</p><p>If you are ordering for a group, send Gownsea the required colours, quantity, and event date. The team can help confirm the best available match and provide a quote before you place your order.</p>',
        ],
        'certificate-gowns' => [
            'description' => 'Prepare for a certificate graduation ceremony with an academic gown for hire or purchase. Gownsea can help graduates and institutions confirm the right size, quantity, and collection or delivery plan.',
            'details' => ['Intended for certificate-level graduation ceremonies', 'Hire and purchase enquiries available', 'Sizing support for individual graduates and groups', 'Confirm ceremony colours and set contents with your institution', 'Plan Nairobi collection or delivery with your quote'],
            'about' => '<p>Mark a certificate graduation with attire that feels appropriate for the occasion. Gownsea’s certificate gowns are offered for hire and purchase, with support to help graduates and organisers plan quantities and sizing ahead of ceremony day.</p><p>Institutional colours and regalia requirements can vary. Check your school’s guidance, then share the event date and number of gowns needed so Gownsea can confirm suitable options and a clear quote.</p>',
        ],
        'diploma-graduation-gowns' => [
            'description' => 'Plan a diploma graduation with gowns available for hire or purchase in Kenya. Get help with sizing, group quantities, and the ceremony details that matter to your college or training institution.',
            'details' => ['For diploma and college graduation ceremonies', 'Hire and purchase enquiries available', 'Sizing support for individual and group orders', 'Confirm institution colours and regalia requirements before ordering', 'Delivery timing arranged around your ceremony date'],
            'about' => '<p>Diploma ceremonies bring together graduates, families, and the institution that has supported their studies. Gownsea helps make attire planning easier with diploma gowns for hire or purchase and practical sizing support for both individuals and groups.</p><p>Tell us your institution, ceremony date, and estimated quantity. We can help check the appropriate style and colour requirements, then prepare a quote and discuss collection or delivery arrangements in Kenya.</p>',
        ],
        'degree-graduation-gowns' => [
            'description' => 'Get ready for a university degree ceremony with graduation gowns for hire or purchase. Gownsea supports graduates and institutions with sizing, group planning, and ceremony-ready regalia in Kenya.',
            'details' => ['Designed for degree conferment and graduation ceremonies', 'Hire and purchase enquiries available', 'Sizing support for graduates and institution orders', 'Check gown and faculty colour requirements with your university', 'Share your event date to plan collection or delivery'],
            'about' => '<p>A degree ceremony is a major milestone, and the right academic attire helps graduates feel ready for the procession, photographs, and celebrations that follow. Gownsea offers degree gowns for hire or purchase, with support for sizing and group requirements.</p><p>Universities set their own regalia and colour guidance, so confirm the details with your institution before ordering. Send Gownsea your ceremony date, quantity, and requirements to receive a tailored quote and arrange the next steps.</p>',
        ],
        'masters-gown' => [
            'description' => 'Celebrate a master’s degree conferment in an academic gown suited to the occasion. Ask Gownsea about hire or purchase, sizing, and planning for individual graduates or university groups.',
            'details' => ['For master’s degree graduations and conferment ceremonies', 'Hire and purchase enquiries available', 'Sizing assistance for individuals and organised groups', 'Confirm university gown and hood requirements before ordering', 'Plan a quote and delivery timing around your event'],
            'about' => '<p>Completing a master’s degree deserves a ceremony look that feels considered and comfortable. Gownsea can help you plan a master’s gown for hire or purchase, whether you are preparing for one graduate or coordinating attire for a university event.</p><p>Regalia details vary between institutions. Check your university’s specifications, then share the required size, quantity, and ceremony date so the team can confirm availability and provide a quote.</p>',
        ],
        'preschool-graduation' => [
            'description' => 'Make a preschool graduation feel special with a child-size gown set for school ceremonies and family photographs. Ask Gownsea to confirm available sizes, colours, set contents, and group quantities.',
            'details' => ['For preschool graduation celebrations and photographs', 'Designed with young graduates in mind', 'Ask the team to confirm available sizes and colours', 'Confirm exactly what is included in the set before ordering', 'Suitable for parent enquiries and school group planning'],
            'about' => '<p>A preschool graduation is a proud moment for children, families, and teachers. A child-size gown set helps make the event memorable and gives families a polished look for the ceremony and photographs.</p><p>For the best fit, share the child’s age or measurements, preferred colour, and event date. Schools planning for a class can provide the number of children and any uniform or colour guidance. Gownsea will confirm available sizes, set contents, and pricing before you order.</p>',
        ],
        'phd-caps' => [
            'description' => 'Complete doctoral regalia with a PhD cap selected to suit your graduation attire. Contact Gownsea to confirm the cap style, colour, availability, and your university requirements.',
            'details' => ['For PhD graduation and doctoral conferment ceremonies', 'Complements a doctoral gown and other academic regalia', 'Confirm style and colour requirements with your university', 'Ask the team to check availability before ordering'],
            'about' => '<p>The doctoral cap is an important finishing piece for PhD regalia. Choose a style that works with your gown and follows your university’s ceremony requirements, especially where faculty or institution colours are specified.</p><p>Share your event date and the cap details provided by your university with Gownsea. The team can confirm which options are available and help arrange a quote for an individual order or a larger ceremony requirement.</p>',
        ],
        'phd-graduation-gown' => [
            'description' => 'Prepare for a PhD conferment with a doctoral graduation gown for hire or purchase. Gownsea can help confirm university specifications, sizing, and arrangements for your ceremony date.',
            'details' => ['For PhD and doctoral graduation ceremonies', 'Hire and purchase enquiries available', 'Sizing and ceremony planning support', 'Confirm doctoral colours and gown style with your university', 'Request a quote based on your event date and requirements'],
            'about' => '<p>A PhD graduation marks years of research and dedication. Gownsea helps doctoral graduates and institutions plan academic attire, with hire and purchase enquiries for PhD gowns and practical support around sizing and event arrangements.</p><p>Doctoral gown styles and colours can differ by university. Check your institution’s requirements, then send Gownsea the relevant details, quantity, and ceremony date. The team can confirm availability and prepare a quote for your needs.</p>',
        ],
        'bachelors-graduation-gown-cap-hood-set' => [
            'description' => 'Prepare for a bachelor’s degree ceremony with a graduation gown, cap, and hood set. Ask Gownsea to confirm university colours, available sizing, and hire or purchase options for your date.',
            'details' => ['Gown, cap, and hood set for bachelor’s degree ceremonies', 'Hire and purchase enquiries available', 'Confirm colours and hood requirements with your university', 'Share your size and ceremony date for planning support', 'Suitable for individual graduates and group enquiries'],
            'about' => '<p>A bachelor’s graduation set brings the key pieces of academic regalia together for the ceremony. This listing includes a gown, cap, and hood, giving graduates a clear starting point when planning attire for the procession and photographs.</p><p>University colours and hood specifications can vary, so check your institution’s requirements before ordering. Contact Gownsea with your size, ceremony date, and quantity to confirm the set details, availability, and quote.</p>',
        ],
        'traditional-barrister-wig-and-gown' => [
            'description' => 'Choose traditional barrister court attire with a wig and gown for advocates and legal professionals. Contact Gownsea to discuss fit, current availability, and the requirements of your practice or occasion.',
            'details' => ['Traditional wig and gown combination for legal practice', 'For advocates and legal professionals', 'Ask about available sizing and fitting support in Nairobi', 'Confirm current availability and quote before ordering'],
            'about' => '<p>Traditional court dress helps advocates present themselves appropriately in formal legal settings. This wig and gown combination is intended for legal professionals who need courtroom attire and want to check fit and availability before making arrangements.</p><p>Court dress requirements can depend on the setting and local practice. Contact Gownsea with the items you need, your preferred timing, and any fitting questions. The team can discuss current options and provide a quote from Nairobi.</p>',
        ],
        'plain-english-bib' => [
            'description' => 'Add a plain English bib to complete traditional court dress for advocates and barristers. Ask Gownsea about fit, compatibility with your legal gown, and current availability before ordering.',
            'details' => ['Plain English style bib for courtroom attire', 'For advocates and barristers', 'Designed as part of formal legal dress', 'Check fit and compatibility with your gown before ordering'],
            'about' => '<p>A bib is a small but visible part of traditional legal attire. This plain English style is intended for advocates and barristers completing their court dress, and can be considered alongside a legal gown and shirt.</p><p>If you are unsure which style is appropriate for your practice, check your professional or court guidance first. Gownsea can help confirm availability and answer questions about fit and coordination with your existing attire.</p>',
        ],
        'advocates-shirt' => [
            'description' => 'Find a white advocates shirt for formal courtroom attire and professional legal wear. Contact Gownsea to check available sizing and how the shirt can be coordinated with your gown and bib.',
            'details' => ['White shirt for advocates and legal professionals', 'Suitable for formal courtroom attire', 'Ask about available sizes before ordering', 'Can be planned alongside a legal gown and bib'],
            'about' => '<p>A white shirt provides a simple foundation for formal legal attire. Advocates can wear it with the appropriate gown and bib for a coordinated courtroom look, while checking that the style follows their professional requirements.</p><p>Contact Gownsea with your size and the other pieces you need. The team can confirm current availability and help you plan a complete legal attire order in Nairobi.</p>',
        ],
        'choral-and-church-attire-pack' => [
            'description' => 'Plan coordinated church or choir attire for your ministry team with a custom group enquiry. Share garment needs, colours, sizes, and quantity so Gownsea can prepare suitable options and a quote.',
            'details' => ['Group attire planning for choirs and ministry teams', 'Discuss garment types, colours, and fitting needs', 'Share sizes and quantities for an accurate group quote', 'Customisation can be discussed for your congregation', 'Delivery planning available by arrangement'],
            'about' => '<p>Coordinated attire can help a choir or ministry team feel unified during services and special occasions. This pack is a starting point for a group enquiry, with garment choices and fitting details discussed around your congregation’s needs.</p><p>Tell Gownsea which garments you need, your preferred colours, the number of people, and the event date. The team can discuss customisation, sizing, availability, and delivery arrangements before preparing a quote.</p>',
        ],
        'undergraduate-academic-hoods' => [
            'description' => 'Complete an undergraduate graduation set with an academic hood in a faculty colour selected to match your university’s guidance. Ask Gownsea about sizing, hire or purchase options, and group orders in Nairobi.',
            'gallery' => [
                '/images/products/academic-gradduation-hoods-hoods-(18)-Photoroom.jpg',
                '/images/products/academic-gradduation-hoods-hoods-(17)-Photoroom.jpg',
                '/images/products/academic-gradduation-hoods-hoods-(16)-Photoroom.jpg',
                '/images/products/academic-gradduation-hoods-hoods-(15)-Photoroom.jpg',
            ],
            'options' => [
                'Faculty colour' => ['Cardinal Red', 'Royal Blue', 'Navy', 'Gold', 'Purple', 'Maroon'],
                'Size' => ['Small', 'Medium', 'Large', 'X-Large'],
            ],
            'details' => [
                'Academic hood for undergraduate degree ceremonies',
                'Faculty colour options to check against your university guidance',
                'Available for hire and purchase enquiries',
                'Pairs with a degree gown and mortarboard',
                'Sizing support for individuals and institution orders',
            ],
            'about' => '<p>An academic hood completes an undergraduate graduation set and adds the faculty colour associated with your degree. Choose a shade that follows your university’s guidance, then pair the hood with a gown and mortarboard for the ceremony, procession, and photographs.</p><p>Gownsea can help graduates and institutions plan hoods for hire or purchase. Share your faculty, required colour, size, quantity, and ceremony date so the team can confirm a suitable option and provide a quote.</p>',
            'fit_note' => 'If you are between sizes, we recommend the larger option for a more comfortable fit over your gown and clothing.',
            'size_guide' => [
                ['size' => 'Small', 'guide' => 'Shorter gowns and petite frames'],
                ['size' => 'Medium', 'guide' => 'Standard undergraduate fit'],
                ['size' => 'Large', 'guide' => 'Taller graduates or bulkier clothing'],
                ['size' => 'X-Large', 'guide' => 'Extra ease over gown and clothing'],
            ],
        ],
    ],

    'journal_posts' => [
        [
            'slug' => 'bulk-hiring-of-gowns-for-institutions-a-cost-effective-and-convenient-solution',
            'title' => 'Bulk Hiring of Gowns for Institutions: A Cost-Effective and Convenient Solution',
            'category' => 'Graduation Attire',
            'date' => '2025-07-11',
            'excerpt' => 'How institutions can reduce logistics pressure while improving graduation-day consistency.',
            'image' => '/images/blogs/2021-08-05.webp',
        ],
        [
            'slug' => 'why-renting-your-graduation-gown-is-a-smart-choice',
            'title' => 'Why Renting Your Graduation Gown is a Smart Choice',
            'category' => 'Graduation Attire',
            'date' => '2025-06-20',
            'excerpt' => 'A practical guide to balancing cost, convenience, and sustainability for graduates.',
        ],
        [
            'slug' => 'what-your-grads-really-think-about-their-gowns-and-why-it-matters',
            'title' => 'What Your Grads Really Think About Their Gowns - And Why It Matters',
            'category' => 'Graduation Attire',
            'date' => '2025-06-14',
            'excerpt' => 'Feedback insights that can improve satisfaction and institutional ceremony quality.',
            'image' => '/images/blogs/img_20211111_163231_401.jpg',
        ],
    ],

    'journal_seo' => [
        'graduation-regalia-boost-tvet-status' => [
            'heading' => 'How Graduation Regalia Can Boost TVET Status in Kenya',
            'title' => 'How Graduation Regalia Boosts TVET Status in Kenya | Gownsea',
            'description' => 'Explore how graduation regalia boosts TVET status in Kenya, celebrates skills, strengthens college identity and supports affordable, dignified ceremonies.',
            'keywords' => [
                'TVET graduation regalia',
                'TVET graduation gowns Kenya',
                'graduation regalia in Kenya',
                'academic regalia for TVET institutions',
                'graduation gown hire for colleges',
                'local garment manufacturing in Kenya',
            ],
        ],
    ],
];
