<?php

return [
    'brand' => [
        'name' => 'Gownsea LTD',
        'primary_color' => '#d42127',
        'phone' => '+254 728 311537',
        'email' => 'hello@gownsea.com',
        'address' => 'Valji Building, Moktar Daddah Street, Nairobi',
        'whatsapp' => '254728311537',
        'logo' => null,
    ],

    'assistant' => [
        'admin_email' => env('ASSISTANT_ADMIN_EMAIL', env('MAIL_FROM_ADDRESS', 'hello@gownsea.com')),
        'faqs' => [
            'Buying process' => 'How do I buy or hire a gown from Gownsea?',
            'Available properties' => 'What categories are currently available?',
            'Pricing' => 'How much does gown hire or purchase cost?',
            'Contact support' => 'How can I quickly contact support?',
        ],
    ],

    'protected_routes' => [
        '/',
        '/about-us',
        '/contact-us',
        '/legal-attire',
        '/graduation-attire',
        '/church-wear',
        '/gown-for-hire',
        '/shop-attire/graduation-attire',
        '/shop-attire/legal-attire',
        '/shop-attire/church-wear',
        '/bulk-inquiry',
        '/the-gown-journal',
        '/the-gown-journal/bulk-hiring-of-gowns-for-institutions-a-cost-effective-and-convenient-solution',
        '/the-gown-journal/why-renting-your-graduation-gown-is-a-smart-choice',
        '/the-gown-journal/what-your-grads-really-think-about-their-gowns-and-why-it-matters',
        '/privacy-policy',
        '/terms-and-conditions',
        '/return-policy',
        '/copyright',

        // Shop Attire (Graduation Attire dropdown)
        '/shop-attire-collection/graduation-attire/graduation-cap',
        '/our-products/graduation-tassels',
        '/our-products/undergraduate-academic-hoods',
        '/shop-attire-collection/graduation-attire/graduation-hoods',
        '/our-products/graduation-stoles',
        '/shop-attire-collection/graduation-attire/phd-caps',
        '/our-products/preschool-graduation',
        '/shop-attire-collection/graduation-attire/pre-school-gowns',
        '/shop-attire-collection/graduation-attire/certificate-gowns',
        '/shop-attire-collection/graduation-attire/diploma-gowns',
        '/shop-attire-collection/graduation-attire/masters-gowns',
        '/shop-attire-collection/graduation-attire/phd-gowns',
        '/our-products/phd-graduation-gown',
        '/shop-attire-collection/graduation-attire/degree-gown',
        '/our-products/degree-graduation-gowns',
        '/our-products/certificate-gowns',
        '/our-products/diploma-graduation-gowns',
        '/our-products/masters-gown',
        '/our-products/phd-caps',

    ],

    'hire_faqs' => [
        'How do I hire a graduation gown?' => 'Head to our gown hire page or bulk inquiry form and we will respond as soon as we can.',
        'How much is it to rent a gown?' => 'It varies by quantity and award level. Graduation hire currently starts from KES 2,500. Send an inquiry for an accurate quote.',
        'What do you wear under a university graduation gown?' => 'Dress smart for a formal occasion. A dark suit or formal dress works well under academic gowns.',
        'How much are graduation gowns in Kenya?' => 'Purchase and hire prices vary by award level. Browse the graduation collection or request a tailored quote.',
    ],

    'clients' => [
        '/images/clients/client-7.png',
        '/images/clients/client-8.png',
        '/images/clients/client-9.png',
        '/images/clients/client-10.png',
        '/images/clients/client-11.png',
        '/images/clients/client-13.png',
        '/images/clients/client-14.jpg',
        '/images/clients/client-15.png',
    ],

    'hire_products' => [
        [
            'slug' => 'graduation-stoles',
            'title' => 'Graduation Stoles',
            'location' => 'Nairobi',
            'price' => 'KES 1,500',
            'cta' => 'Request Gown Now',
            'description' => 'Ceremony-ready stoles to complete academic sets for hire or purchase.',
            'category' => 'graduation',
            'image' => '/images/products/Gownsea-custom-graduation-stoles-(23).png',
            'url' => '/our-products/graduation-stoles',
        ],
        [
            'slug' => 'graduation-tassels',
            'title' => 'Graduation Tassels',
            'location' => 'Nairobi',
            'price' => 'KES 350',
            'cta' => 'Request Gown Now',
            'description' => 'Colour-matched tassels for mortarboards across award levels.',
            'category' => 'graduation',
            'image' => '/images/products/graduation-tassels-from-gownsea-(4)-Photoroom-(1).jpg',
            'url' => '/our-products/graduation-tassels',
        ],
        [
            'slug' => 'certificate-gowns',
            'title' => 'Certificate Gowns',
            'location' => 'Nairobi',
            'price' => 'KES 2,500',
            'cta' => 'Hire Graduation Attire',
            'description' => 'Certificate-level gowns available for hire and sale.',
            'category' => 'graduation',
            'image' => '/images/products/Gownsea-certificate-graduation-gowns-black-(7).png',
            'url' => '/shop-attire-collection/graduation-attire/certificate-gowns',
        ],
        [
            'slug' => 'diploma-graduation-gowns',
            'title' => 'Diploma Graduation Gowns',
            'location' => 'Nairobi',
            'price' => 'KES 2,000',
            'cta' => 'Hire Graduation Attire',
            'description' => 'Diploma gowns prepared for ceremony hire with reliable sizing support.',
            'category' => 'graduation',
            'image' => '/images/products/Gownsea-diploma-graduation-gowns-(10)-Photoroom.png',
            'url' => '/shop-attire-collection/graduation-attire/diploma-gowns',
        ],
        [
            'slug' => 'degree-graduation-gowns',
            'title' => 'Degree Graduation Gowns',
            'location' => 'Nairobi',
            'price' => 'KES 3,000',
            'cta' => 'Hire Graduation Attire',
            'description' => 'University-standard degree gowns for hire across Kenyan institutions.',
            'category' => 'graduation',
            'image' => '/images/products/graduation-gowns-by-Gownsea-Caroline-muthoni-(42).1.png',
            'url' => '/our-products/degree-graduation-gowns',
        ],
        [
            'slug' => 'masters-gown',
            'title' => 'Masters Gown',
            'location' => 'Nairobi',
            'price' => 'KES 3,000',
            'cta' => 'Hire Graduation Attire',
            'description' => 'Masters gowns with the right academic finish for conferment ceremonies.',
            'category' => 'graduation',
            'image' => '/images/products/Masters-Graduation-(5)-Photorooms.png',
            'url' => '/our-products/masters-gown',
        ],
        [
            'slug' => 'preschool-graduation',
            'title' => 'Preschool Graduation',
            'location' => 'Nairobi',
            'price' => 'KES 2,500',
            'cta' => 'Hire Graduation Attire',
            'description' => 'Child-ready preschool graduation sets for schools and parents.',
            'category' => 'graduation',
            'image' => '/images/products/Preschool-graduation-gown-and-sash-(1).png',
            'url' => '/our-products/preschool-graduation',
        ],
        [
            'slug' => 'phd-caps',
            'title' => 'PHD Caps',
            'location' => 'Nairobi',
            'price' => 'KES 1,500',
            'cta' => 'Request Gown Now',
            'description' => 'Doctoral caps and bonnets to complete PhD regalia.',
            'category' => 'graduation',
            'image' => '/images/products/PhD-Graduation-cap.-Gownsea-ltd-(9)-Photoroom.jpg',
            'url' => '/shop-attire-collection/graduation-attire/phd-caps',
        ],
        [
            'slug' => 'phd-graduation-gown',
            'title' => 'PHD Graduation Gown',
            'location' => 'Nairobi',
            'price' => 'KES 4,000',
            'cta' => 'Hire Graduation Attire',
            'description' => 'Doctoral gowns for hire with a distinguished ceremonial finish.',
            'category' => 'graduation',
            'image' => '/images/products/PhD-Doctorate-graduation-gown-clergy-(20)-Photoroom.jpg',
            'url' => '/our-products/phd-graduation-gown',
        ],
        [
            'slug' => 'undergraduate-academic-hoods',
            'title' => 'Undergraduate Academic Hoods',
            'location' => 'Nairobi',
            'price' => 'KES 3,000',
            'cta' => 'Request Gown Now',
            'description' => 'Faculty-colour undergraduate hoods to complete degree sets.',
            'category' => 'graduation',
            'image' => '/images/products/academic-gradduation-hoods-hoods-(18)-Photoroom.jpg',
            'url' => '/our-products/undergraduate-academic-hoods',
        ],
    ],

    'properties' => [
        [
            'slug' => 'bachelors-graduation-gown-cap-hood-set',
            'title' => 'Bachelors Graduation Gown, Cap & Hood Set',
            'location' => 'Nairobi',
            'price' => 'KES 12,500',
            'cta' => 'Reserve Set',
            'description' => 'University-standard complete set for ceremonies and photo sessions.',
            'category' => 'graduation',
            'image' => '/images/products/graduation-gowns-by-Gownsea-Caroline-muthoni-(42).1.png',
            'url' => '/shop-attire-collection/graduation-attire/degree-gown',
        ],
        [
            'slug' => 'traditional-barrister-wig-and-gown',
            'title' => 'Traditional Barrister Wig & Gown',
            'location' => 'Nairobi CBD',
            'price' => 'KES 38,000',
            'cta' => 'Request Quote',
            'description' => 'Premium courtroom-ready legal attire tailored for professional use.',
            'category' => 'legal',
            'image' => '/images/site/barrister-wig.jpg',
            'url' => '/shop-attire/legal-attire',
        ],
        [
            'slug' => 'plain-english-bib',
            'title' => 'Bib',
            'location' => 'Nairobi',
            'price' => 'Request quote',
            'cta' => 'Shop Legal Wear',
            'description' => 'Courtroom bibs for advocates and barristers.',
            'category' => 'legal',
            'image' => '/images/products/Plain-English-Bib-New-1.jpg',
            'url' => '/shop-attire/legal-attire',
        ],
        [
            'slug' => 'advocates-shirt',
            'title' => 'Advocates Shirt',
            'location' => 'Nairobi',
            'price' => 'Request quote',
            'cta' => 'Shop Legal Wear',
            'description' => 'White advocates shirts for professional courtroom wear.',
            'category' => 'legal',
            'image' => '/images/products/advocate-white-shirts.jpeg',
            'url' => '/shop-attire/legal-attire',
        ],
        [
            'slug' => 'choral-and-church-attire-pack',
            'title' => 'Choral & Church Attire Pack',
            'location' => 'Nationwide Delivery',
            'price' => 'KES 8,700',
            'cta' => 'Order Pack',
            'description' => 'Elegant church wear with customized fitting for ministry teams.',
            'category' => 'church',
            'image' => '/images/products/Gownsea-church-wear-(1).png',
            'url' => '/shop-attire/church-wear',
        ],
    ],

    'product_profiles' => [
        'undergraduate-academic-hoods' => [
            'gallery' => [
                '/images/products/academic-gradduation-hoods-hoods-(18)-Photoroom.jpg',
                '/images/products/academic-gradduation-hoods-hoods-(17)-Photoroom.jpg',
                '/images/products/academic-gradduation-hoods-hoods-(16)-Photoroom.jpg',
                '/images/products/academic-gradduation-hoods-hoods-(15)-Photoroom.jpg',
            ],
            'options' => [
                'Faculty colour' => ['Cardinal Red', 'Royal Blue', 'Navy', 'Gold', 'Purple', 'Maroon'],
                'Size' => ['Small', 'Medium', 'Large', 'X-Large'],
            ],
            'details' => [
                'Traditional undergraduate academic hood',
                'Faculty-colour lining to match your award',
                'Durable and comfortable for a full ceremony day',
                'Available for hire and purchase',
                'Pairs with degree gowns and mortarboards',
            ],
            'about' => 'Your graduation look is not complete without the academic hood. Gownsea undergraduate hoods are cut to traditional specifications, with faculty colours that represent your discipline. Whether this is your first conferment or a repeat hire for an institution, the hood gives the ceremony its official finish — ready for the hall, the photographs, and the procession.',
            'fit_note' => 'If you are between sizes, we recommend the larger option for a more comfortable fit over your gown and clothing.',
            'size_guide' => [
                ['size' => 'Small', 'guide' => 'Shorter gowns and petite frames'],
                ['size' => 'Medium', 'guide' => 'Standard undergraduate fit'],
                ['size' => 'Large', 'guide' => 'Taller graduates or bulkier clothing'],
                ['size' => 'X-Large', 'guide' => 'Extra ease over gown and clothing'],
            ],
        ],
    ],

    'journal_posts' => [
        [
            'slug' => 'bulk-hiring-of-gowns-for-institutions-a-cost-effective-and-convenient-solution',
            'title' => 'Bulk Hiring of Gowns for Institutions: A Cost-Effective and Convenient Solution',
            'category' => 'Graduation Attire',
            'date' => '2025-07-11',
            'excerpt' => 'How institutions can reduce logistics pressure while improving graduation-day consistency.',
            'image' => '/images/blogs/2021-08-05.webp',
        ],
        [
            'slug' => 'why-renting-your-graduation-gown-is-a-smart-choice',
            'title' => 'Why Renting Your Graduation Gown is a Smart Choice',
            'category' => 'Graduation Attire',
            'date' => '2025-06-20',
            'excerpt' => 'A practical guide to balancing cost, convenience, and sustainability for graduates.',
        ],
        [
            'slug' => 'what-your-grads-really-think-about-their-gowns-and-why-it-matters',
            'title' => 'What Your Grads Really Think About Their Gowns - And Why It Matters',
            'category' => 'Graduation Attire',
            'date' => '2025-06-14',
            'excerpt' => 'Feedback insights that can improve satisfaction and institutional ceremony quality.',
            'image' => '/images/blogs/img_20211111_163231_401.jpg',
        ],
    ],
];
